<?php

namespace Database\Seeders;

use App\Models\Area;
use Illuminate\Database\Seeder;

class AreaTableSeeder extends Seeder
{
    public function run()
    {
        $area = [
            [
                'id'                 => 1,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Ayer Baloi',
                'postcode'           => '82100',
            ],
            [
                'id'                 => 2,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Ayer Hitam',
                'postcode'           => '86100',
            ],
            [
                'id'                 => 3,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Ayer Tawar 2',
                'postcode'           => '81920',
            ],
            [
                'id'                 => 4,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Ayer Tawar 3',
                'postcode'           => '81920',
            ],
            [
                'id'                 => 5,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Ayer Tawar 4',
                'postcode'           => '81920',
            ],
            [
                'id'                 => 6,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Ayer Tawar 5',
                'postcode'           => '81920',
            ],
            [
                'id'                 => 7,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Bandar Penawar',
                'postcode'           => '81930',
            ],
            [
                'id'                 => 8,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Bandar Tenggara',
                'postcode'           => '81440',
            ],
            [
                'id'                 => 9,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Batu Anam',
                'postcode'           => '85100',
            ],
            [
                'id'                 => 10,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Batu Pahat',
                'postcode'           => '83000',
            ],
            [
                'id'                 => 11,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Bekok',
                'postcode'           => '86500',
            ],
            [
                'id'                 => 12,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Benut',
                'postcode'           => '82200',
            ],
            [
                'id'                 => 13,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Bukit Gambir',
                'postcode'           => '84800',
            ],
            [
                'id'                 => 14,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Bukit Pasir',
                'postcode'           => '84300',
            ],
            [
                'id'                 => 15,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Chaah',
                'postcode'           => '85400',
            ],
            [
                'id'                 => 16,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Endau',
                'postcode'           => '86900',
            ],
            [
                'id'                 => 17,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Gelang Patah',
                'postcode'           => '81550',
            ],
            [
                'id'                 => 18,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Gerisek',
                'postcode'           => '84700',
            ],
            [
                'id'                 => 19,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Gugusan Taib Andak',
                'postcode'           => '81450',
            ],
            [
                'id'                 => 20,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Jementah',
                'postcode'           => '85200',
            ],
            [
                'id'                 => 21,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80000',
            ],
            [
                'id'                 => 22,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80050',
            ],
            [
                'id'                 => 23,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80100',
            ],
            [
                'id'                 => 24,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80150',
            ],
            [
                'id'                 => 25,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80200',
            ],
            [
                'id'                 => 26,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80250',
            ],
            [
                'id'                 => 27,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80300',
            ],
            [
                'id'                 => 28,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80350',
            ],
            [
                'id'                 => 29,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80400',
            ],
            [
                'id'                 => 30,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80500',
            ],
            [
                'id'                 => 31,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80506',
            ],
            [
                'id'                 => 32,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80508',
            ],
            [
                'id'                 => 33,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80516',
            ],
            [
                'id'                 => 34,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80519',
            ],
            [
                'id'                 => 35,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80534',
            ],
            [
                'id'                 => 36,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80536',
            ],
            [
                'id'                 => 37,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80542',
            ],
            [
                'id'                 => 38,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80546',
            ],
            [
                'id'                 => 39,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80558',
            ],
            [
                'id'                 => 40,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80560',
            ],
            [
                'id'                 => 41,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80564',
            ],
            [
                'id'                 => 42,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80568',
            ],
            [
                'id'                 => 43,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80578',
            ],
            [
                'id'                 => 44,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80584',
            ],
            [
                'id'                 => 45,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80586',
            ],
            [
                'id'                 => 46,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80590',
            ],
            [
                'id'                 => 47,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80592',
            ],
            [
                'id'                 => 48,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80594',
            ],
            [
                'id'                 => 49,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80596',
            ],
            [
                'id'                 => 50,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80600',
            ],
            [
                'id'                 => 51,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80604',
            ],
            [
                'id'                 => 52,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80608',
            ],
            [
                'id'                 => 53,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80620',
            ],
            [
                'id'                 => 54,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80622',
            ],
            [
                'id'                 => 55,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80628',
            ],
            [
                'id'                 => 56,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80644',
            ],
            [
                'id'                 => 57,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80648',
            ],
            [
                'id'                 => 58,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80662',
            ],
            [
                'id'                 => 59,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80664',
            ],
            [
                'id'                 => 60,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80668',
            ],
            [
                'id'                 => 61,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80670',
            ],
            [
                'id'                 => 62,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80672',
            ],
            [
                'id'                 => 63,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80673',
            ],
            [
                'id'                 => 64,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80676',
            ],
            [
                'id'                 => 65,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80700',
            ],
            [
                'id'                 => 66,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80710',
            ],
            [
                'id'                 => 67,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80720',
            ],
            [
                'id'                 => 68,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80730',
            ],
            [
                'id'                 => 69,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80900',
            ],
            [
                'id'                 => 70,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80902',
            ],
            [
                'id'                 => 71,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80904',
            ],
            [
                'id'                 => 72,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80906',
            ],
            [
                'id'                 => 73,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80908',
            ],
            [
                'id'                 => 74,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80988',
            ],
            [
                'id'                 => 75,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '80990',
            ],
            [
                'id'                 => 76,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '81000',
            ],
            [
                'id'                 => 77,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '81100',
            ],
            [
                'id'                 => 78,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '81200',
            ],
            [
                'id'                 => 79,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '81300',
            ],
            [
                'id'                 => 80,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Johor Bahru',
                'postcode'           => '81310',
            ],
            [
                'id'                 => 81,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Kahang',
                'postcode'           => '86700',
            ],
            [
                'id'                 => 82,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Kluang',
                'postcode'           => '86000',
            ],
            [
                'id'                 => 83,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Kluang',
                'postcode'           => '86300',
            ],
            [
                'id'                 => 84,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Kota Tinggi',
                'postcode'           => '81900',
            ],
            [
                'id'                 => 85,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Kukup',
                'postcode'           => '82300',
            ],
            [
                'id'                 => 86,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Kulai',
                'postcode'           => '81000',
            ],
            [
                'id'                 => 87,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Labis',
                'postcode'           => '85300',
            ],
            [
                'id'                 => 88,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Layang-Layang',
                'postcode'           => '81850',
            ],
            [
                'id'                 => 89,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Masai',
                'postcode'           => '81750',
            ],
            [
                'id'                 => 90,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Masai',
                'postcode'           => '81750',
            ],
            [
                'id'                 => 91,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Mersing',
                'postcode'           => '86800',
            ],
            [
                'id'                 => 92,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Mersing',
                'postcode'           => '86810',
            ],
            [
                'id'                 => 93,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Muar',
                'postcode'           => '84000',
            ],
            [
                'id'                 => 94,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Muar',
                'postcode'           => '84200',
            ],
            [
                'id'                 => 95,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79000',
            ],
            [
                'id'                 => 96,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79100',
            ],
            [
                'id'                 => 97,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79150',
            ],
            [
                'id'                 => 98,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79200',
            ],
            [
                'id'                 => 99,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79250',
            ],
            [
                'id'                 => 100,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79502',
            ],
            [
                'id'                 => 101,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79503',
            ],
            [
                'id'                 => 102,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79504',
            ],
            [
                'id'                 => 103,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79505',
            ],
            [
                'id'                 => 104,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79511',
            ],
            [
                'id'                 => 105,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79513',
            ],
            [
                'id'                 => 106,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79514',
            ],
            [
                'id'                 => 107,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79517',
            ],
            [
                'id'                 => 108,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79518',
            ],
            [
                'id'                 => 109,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79520',
            ],
            [
                'id'                 => 110,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79521',
            ],
            [
                'id'                 => 111,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79523',
            ],
            [
                'id'                 => 112,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79532',
            ],
            [
                'id'                 => 113,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79538',
            ],
            [
                'id'                 => 114,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79540',
            ],
            [
                'id'                 => 115,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79546',
            ],
            [
                'id'                 => 116,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79548',
            ],
            [
                'id'                 => 117,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79550',
            ],
            [
                'id'                 => 118,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79552',
            ],
            [
                'id'                 => 119,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79555',
            ],
            [
                'id'                 => 120,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79570',
            ],
            [
                'id'                 => 121,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79575',
            ],
            [
                'id'                 => 122,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79576',
            ],
            [
                'id'                 => 123,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79592',
            ],
            [
                'id'                 => 124,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79601',
            ],
            [
                'id'                 => 125,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79603',
            ],
            [
                'id'                 => 126,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79605',
            ],
            [
                'id'                 => 127,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79606',
            ],
            [
                'id'                 => 128,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79612',
            ],
            [
                'id'                 => 129,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79626',
            ],
            [
                'id'                 => 130,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79630',
            ],
            [
                'id'                 => 131,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79632',
            ],
            [
                'id'                 => 132,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79646',
            ],
            [
                'id'                 => 133,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79658',
            ],
            [
                'id'                 => 134,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79660',
            ],
            [
                'id'                 => 135,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79680',
            ],
            [
                'id'                 => 136,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79681',
            ],
            [
                'id'                 => 137,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Nusajaya',
                'postcode'           => '79683',
            ],
            [
                'id'                 => 138,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Pagoh',
                'postcode'           => '84600',
            ],
            [
                'id'                 => 139,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Paloh',
                'postcode'           => '86600',
            ],
            [
                'id'                 => 140,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Panchor',
                'postcode'           => '84500',
            ],
            [
                'id'                 => 141,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Parit Jawa',
                'postcode'           => '84150',
            ],
            [
                'id'                 => 142,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Parit Raja',
                'postcode'           => '86400',
            ],
            [
                'id'                 => 143,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Parit Sulong',
                'postcode'           => '83500',
            ],
            [
                'id'                 => 144,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Pasir Gudang',
                'postcode'           => '81700',
            ],
            [
                'id'                 => 145,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Pekan Nenas',
                'postcode'           => '81500',
            ],
            [
                'id'                 => 146,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Pengerang',
                'postcode'           => '81600',
            ],
            [
                'id'                 => 147,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Pontian',
                'postcode'           => '82000',
            ],
            [
                'id'                 => 148,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Rengam',
                'postcode'           => '86300',
            ],
            [
                'id'                 => 149,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Rengit',
                'postcode'           => '83100',
            ],
            [
                'id'                 => 150,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Segamat',
                'postcode'           => '85000',
            ],
            [
                'id'                 => 151,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Semerah',
                'postcode'           => '83600',
            ],
            [
                'id'                 => 152,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Senai',
                'postcode'           => '81400',
            ],
            [
                'id'                 => 153,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Senggarang',
                'postcode'           => '83200',
            ],
            [
                'id'                 => 154,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Seri Gading',
                'postcode'           => '83300',
            ],
            [
                'id'                 => 155,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Seri Medan',
                'postcode'           => '83400',
            ],
            [
                'id'                 => 156,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Simpang Rengam',
                'postcode'           => '86200',
            ],
            [
                'id'                 => 157,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Sri Gading',
                'postcode'           => '83300',
            ],
            [
                'id'                 => 158,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Sri Medan',
                'postcode'           => '83400',
            ],
            [
                'id'                 => 159,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Sungai Mati',
                'postcode'           => '81500',
            ],
            [
                'id'                 => 160,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Sungai Mati',
                'postcode'           => '84400',
            ],
            [
                'id'                 => 161,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Tangkak',
                'postcode'           => '84000',
            ],
            [
                'id'                 => 162,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Tangkak',
                'postcode'           => '84900',
            ],
            [
                'id'                 => 163,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Ulu Tiram',
                'postcode'           => '81800',
            ],
            [
                'id'                 => 164,
                'country'            => 'Malaysia',
                'states'             => 'Johor',
                'area'               => 'Yong Peng',
                'postcode'           => '83700',
            ],
        ];

        Area::insert($area);
    }
}
